export const BROWSER = 'Browser'
export const TYPE = 'type'
export const NAME = 'name'
export const MODEL = 'model'
export const VERSION = 'version'
export const VENDOR = 'vendor'
export const UNKNOWN = 'UNKNOWN'
